### ISSUE TITLE
Add a new section on goals and non-goals

### ISSUE THREAD

**Issue by Kevsy** [salvatoreloreto/IETFdrafts#2]
##### Reason:

Add new section on goals/non-goals. i.e. why we are doing this, and what we are not doing
##### Suggested text for new section:

_start_
#### Goals and non-goals

The primary goal is to define an intermediary to TLS-protected 'http' traffic, that operates with the knowledge 
and explicit consent of the user

Non-goals are to define an intermediary for unprotected 'http' traffic over both HTTP/1.1 and HTTP/2, and for 'https' URIs. However the intermediary's expected behaviour for these cases is listed for completeness. 

_end_

**Comment by salvatoreloreto** [comment]
inserted a Goals non-goals section;  the http clear text is in as a goal at moment
