### ISSUE TITLE
Change terminology entry for EAP

### ISSUE THREAD

**Issue by Kevsy** [salvatoreloreto/IETFdrafts#7]
##### Reason

As per issue 8 , the shorter introduction leaves the formal definition of the EAP to theTerminology section. The formal reference to 'proxies' should be used in the 'Explicit proxy' definition as that comes first
##### Suggested change

> 1. Terminology

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in [RFC2119].

This document defines the following terms:

Explicit proxy:   an intercepting proxy (see section 2.3 [I-D.ietf-httpbis-p1-messaging]) that 
communicates its presence to the user agent and destination server.

Explicitly Authenticated Proxy: an HTTP Proxy  that is certificate authenticated, user acknowledged > and connected to over a TLS encrypted (and possibly integrity protected) connection.  An Explicitly Authenticated Proxy is configured by the user agent to
   exclusively receive "http" URI scheme requests and attempt to satisfy
   those requests on behalf of the user agent. The presence of a configured Explicitly Authenticated Proxy MUST NOT change the user agent behaviour for the "https" URI scheme requests.

**Comment by salvatoreloreto** [comment]
updated the terminology section accordingly
