### ISSUE TITLE
What is the expected behaviour for non-TLS protected http URIs?

### ISSUE THREAD

**Issue by Kevsy** [salvatoreloreto/IETFdrafts#9]
##### Type: question, enhancement

What is the EAP's expected behaviour for non-TLS protected http URIs? We should at least mention this, and consider the security implications carefully.  For example (option 1):

> Section 4.4 Explicitly Authenticated Proxy for non-secured http requests 
> In this case the Proxy will create a secure connection to the client, but will not negotiate > a secure connection to the origin server. _plus diagram_

**But** this behaviour may lead the user to believe that they are in fact securely connected to the origin server, for example if a padlock is shown based on the secure connection to the proxy.

So option 2: 

> Section 4.4 Explicitly Authenticated Proxy for non-secured http requests
> Where the 'http' request is not secured by the origin server, the Proxy will drop the 
> secure connection to the client and revert to its regular behaviour for non-secured 'http' requests

 **But** what would be the impact of the secure connection dropping?

**Comment by salvatoreloreto** [comment]
This behavior mimic the Google DCP (or SPDY proxy) behavior

**Comment by Kevsy** [comment]
Thanks Salvatore - I should explain what I mean more clearly:

If the user makes a request to http://example.com , and the user is not using a browser proxy, then what is the expected behaviour of the EAP?
